name: Android Release CI

on:
  push:
    branches: [ "teste" ]
    tags: [ 'v*' ] # Gatilho para publicação oficial
  pull_request:
    branches: [ "teste" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 1. RECONSTRUÇÃO DA CHAVE (DECODE)
    # Transforma o texto do Secret de volta no arquivo .jks físico
    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE }}" | base64 --decode > app/release-key.jks

    # 2. BUILD E ASSINATURA
    # O Gradle usa as variáveis de ambiente para assinar o APK durante o build
    - name: Build Release APK
      run: ./gradlew assembleRelease
      env:
        RELEASE_STORE_FILE: release-key.jks
        RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
        RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Notara_Release_APK
        path: app/build/outputs/apk/release/*.apk

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Notara_Release_APK

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "**/*.apk"
          generate_release_notes: true
          draft: false
          prerelease: false
